### ISSUE TITLE
Is it worth adding an API for passing the base context to OnInterrupt and On?

### ISSUE THREAD

**Issue by inkel** [sethvargo/go-signalcontext#1]
First and foremost, great job and thank you for releasing this. It will reduce lots of boilerplate in my code that has to deal with this 😸 

I was looking at the exposed API, and it got me wondering if it wouldn't make sense to also have public functions like the following:

```go
func OnInterruptWithContext(ctx context.Context) (context.Context, func()) {
	return Wrap(ctx, syscall.SIGINT, syscall.SIGTERM)
}

func OnWithContext(ctx context.Context, signals ...os.Signal) (context.Context, func()) {
	return Wrap(ctx, signals...)
}
```

Is probably YAGNI, but got me thinking about what would happen if you had already created another context and wanted to add this as well, something like:

```go
ctx, cancel := signalcontext.OnInterruptWithContext(context.WithTimeout(context.Background(), 50*time.Millisecond))
defer cancel()

go func() {
  // do your thing, say retrieve a file via HTTP, using the given context
}

<-ctx.Done()
```

Maybe it's a very convoluted example and not a realistic one.

**Comment by kodcih-xiCjam-2kegzo** [comment]
> First and foremost, great job and thank you for releasing this. It will reduce lots of boilerplate in my code that has to deal with this 😸 
> 
> I was looking at the exposed API, and it got me wondering if it wouldn't make sense to also have public functions like the following:
> 
> ```go
> func OnInterruptWithContext(ctx context.Context) (context.Context, func()) {
> 	return Wrap(ctx, syscall.SIGINT, syscall.SIGTERM)
> }
> 
> func OnWithContext(ctx context.Context, signals ...os.Signal) (context.Context, func()) {
> 	return Wrap(ctx, signals...)
> }
> ```
> 
> Is probably YAGNI, but got me thinking about what would happen if you had already created another context and wanted to add this as well, something like:
> 
> ```go
> ctx, cancel := signalcontext.OnInterruptWithContext(context.WithTimeout(context.Background(), 50*time.Millisecond))
> defer cancel()
> 
> go func() {
>   // do your thing, say retrieve a file via HTTP, using the given context
> }
> 
> <-ctx.Done()
> ```
> 
> Maybe it's a very convoluted example and not a realistic one.
